name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

  lint-unused-code:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download periphery
        run: |
          apt install wget
          wget https://github.com/peripheryapp/periphery/releases/download/2.16.0/periphery-2.16.0.zip

      - name: Unzip binary
        run: |
          unzip periphery-2.16.0.zip

      - name: Move binary to workspace
        run: |
          mv periphery $GITHUB_WORKSPACE/periphery

      - name: Run periphery
        run: |
          cd $GITHUB_WORKSPACE
          ./periphery scan --strict SUPPORTS_MACCATALYST=NO
          
