name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

  lint-unused-code:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9

    env:
      version: "2.16.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: irgaly/setup-mint@v1

      - name: Run periphery
        run: |
          periphery scan --strict SUPPORTS_MACCATALYST=NO
          
