name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

  lint-unused-code:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9

    env:
      MINT_PATH: "/github/home/.mint"
      MINT_LINK_PATH: "/github/home/.mint/bin"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: irgaly/setup-mint@v1

      - name: Run periphery
        run: |
          mint run periphery scan --strict
